# IDS Assignment Part 1 - <font color="red"><h7>Deadline: 18/12/2022 23:59</h7></font>
This is the first part of the assignments in IDS 2022/2023. 
Please use this Jupyter notebook to work on the questions posed in the assignment. When you are done, upload the notebook in Moodle at the designated activity. This is the _only_ file that is required. A separate report is _not_ needed and will not be considered for grading. 

Give your commented Python code and answers in the corresponding provided cells. Make sure to answer all questions in a clear and explicit manner and discuss your outputs. _Please do not change the general structure of this notebook_. You can, however, add additional markdown or code cells if necessary. <b>Please DO NOT CLEAR THE OUTPUT of the notebook you are submitting! </b>

<font color="red"> *Please make sure to include the names and matriculation numbers of all group members in the slot provided below.* </font> If a name or a student id is missing, the student will not receive any points.

Hint 1: While working on the assignment, you will get a better understanding of the dataset. Feel free to generate additional results and visualizations to support your answers. For example, this might be useful regarding data modification, data simplification, or output interpretation. <font color="red">Ensure that all your claims are supported.</font>

Hint 2: <font color="red">Plan your time wisely. </font> A few parts of this assignment may take some time to run. It might be necessary to consider time management when you plan your group work. Also, do not attempt to upload your assignment at the last minute before the deadline. This often does not work, and you will miss the deadline. Late submissions will not be considered.

Hint 3: RWTHmoodle allows multiple submissions, with every new submission overwriting the previous one. <b>Partial submissions are therefore possible and encouraged. </b> This might be helpful in case of technical issues with RWTHMoodle, which may occur close to the deadline.

<font color="red"><b>Student Names and IDs:
    
    1. Po-Yen Chen 429195
    
    2. 
    
    3.

For those using Jupyter Notebook in your local environments, please install the following library in your environment:
```pip install umap-learn==0.5.3```

In [1]:
#your imports (only use libraries provided in the environment)
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Pricing your AirBnB

You finally made it! Working as a data scientist at an established process mining company in New York, you earned so much money that you can buy a flat for yourself. You decide to buy a 2-room apartment in Manhattan. Congratulations!

Currently, you are still living in your rental apartment and are tied to a long-running rental contract. You can only use the apartment in 5 years from now. Therefore, you want to use the apartment as an AirBnB in the meantime, generating some consistent income. 


You have no clue how you should price your AirBnB per night (you are living in New York, so you never needed to book an AirBnB). You decide to leverage your unique skill set and perform a data-driven, informed decision. You collect all the data you can get your hands on by traversing all New York apartments. The retrieved data set **AirBnB_original.csv** is your starting point for investigation.

## Question 1: Exploring the Data Set (18 points)

As with every data set, you first want to know what you are dealing with. You perform some exploratory data analysis and clean the data along the way.

Show a few data points contained in the data set. Include all attributes. **(0.5 point)**

In [ ]:
# Your answer goes here

AirBnB_original = pd.read_csv('AirBnB_original.csv')
print(AirBnB_original.shape)
print(AirBnB_original.head())

### Basic Cleaning (4 points)

First, you have to remove NaN entries across the data set such that we only keep rows without any NaN value. How many rows did you remove? **(0.5 points)**

In [ ]:
# Your answer goes here
AirBnB_original = AirBnB_original.dropna()
AirBnB_original = AirBnB_original.reset_index(drop=True)
print(AirBnB_original.shape)
print('We remove 1477 NaN dataset.')

Since duplicated entries are misleading, we want to remove duplicate flats (identified by their id), such that we only keep them once and create a new dataset. How many duplicates are removed? **(0.5 point)**

In [ ]:
# Your answer goes here
AirBnB_original = AirBnB_original.drop_duplicates(keep='first', inplace=False)
print(AirBnB_original.shape)
print('We removes 273 duplicated dataset.')

From now on, you work with the dataset **AirBnB_cleaned.csv**.

To get a feeling for nightly prices in New York, you take a look at the price attribute. Calculate the average price, the first and third quantiles, and the standard deviation. **(1 point)**

In [2]:
# Your answer goes here
AirBnB_cleaned = pd.read_csv('AirBnB_cleaned.csv')
price = AirBnB_cleaned.price
s = np.sum(price)

# Calculate the average price
print('The average price is', round(s/70842))

# Calculate the first, the third percentile
p1 = np.percentile(price, 25)
p2 = np.percentile(price, 75)
print('The first, the third percentile are', round(p1),'and', round(p2), ', respectively.')
      
# Calculate the standard deviation
std = np.std(price)
print('The standard deviation is', round(std,2))

The average price is 625
The first, the third percentile are 340 and 913 , respectively.
The standard deviation is 331.23


You want to get a more visual picture of the price range. Use a histogram and boxplot to show the distribution of prices on the entire dataset. **(2 points)**

In [ ]:
# Your answer goes here
# Histogram
sns.displot(data=price, kind="hist")

In [ ]:
# Boxplot
plt.boxplot(price)

### Exploring Price Relationships (3 points)

To inform our pricing decision, we want to investigate some differentiating factors for pricing apartments.

Since you have an overview of the prices and their distribution, you want to investigate which features of your dataset you might use to make your pricing decision. To do so, discuss each feature of the dataset and already rule out features that will definitely not impact the pricing decision. Below you can find a brief description of each feature: 

- id: Unique identifier for an apartment
- host id: Identifier of the host offering a certain apartment
- neighborhood group: Name of a neighborhood group in which an apartment is located
- neighborhood: More fine-grained view on neighborhoods than neighborhood group
- lat: Latitude coordinate of an apartment
- long: Longitude coordinate of an apartment
- country: The country in which an apartment is located
- country code: Code of the country in which an apartment is located
- instant bookable: Boolean values if an apartment is instantly bookable
- cancellation policy: Policy for cancellation of booking
- room type: Type of apartment/room
- construction year: Year of construction of apartment
- price: Price for renting an apartment
- service fee: Fee of service
- minimum nights: Number of minimum nights to rent an apartment
- number of reviews: Number of reviews for an apartment
- review rate number:  Review rate for an apartment (1 to 5)
- calculated host listings count: Number of listings a host has
- number rooms: Number of rooms in an apartment


In [ ]:
# Your answer goes here


_Answer:_ Intuitively, the id and the host id would definitely no effect on price decision. Other features we have to plot the graph to decide their relationship.


### Univariate Analysis (4.5 points)

In the following, you want to analyze which features influence the price. You do this univariately, i.e., look at the relationship between one feature and the price individually. No matter which features you concluded to be useful in the last task, **you will consider the following seven features: service fee, minimum nights, neighborhood group, room type, cancellation policy, construction year, and the number of rooms.**

First, we look closely at the relationship between price and service fee. To do so, create a joint plot for these two attributes. What is your finding? Is this a helpful feature for our pricing decision? **(1 point)**

In [ ]:
# Your answer goes here
sns.jointplot(data=AirBnB_cleaned, x='price', y="service fee", kind='kde');

_Answer:_ The price and the service fee have positive correlation.



Next, we are interested in the relationship between the number of minimum nights and the price. To analyze it, create a joint plot with a regression. Describe your observation. **(1 point)**

In [ ]:
# Your answer goes here
sns.jointplot(data=AirBnB_cleaned, x='minimum nights', y="price", kind='reg');

_Answer_: Minimum nights and the price have no direct relationship.



To further investigate the pricing decision, you look at the remaining five features: neighborhood group, room type, cancellation policy, construction year, and the number of rooms.
To get an overview, you decide to create box plots (including the mean) for each of these features to visualize their influence on the price. Describe your findings. Which values of the features influence the price? **(2.5 point)**

In [ ]:
# Your answer goes here
# create box plots (including the mean) for each of these features to visualize their influence on the price
sns.boxplot(x="neighborhood group", y="price", data=AirBnB_cleaned)


In [ ]:
sns.boxplot(x="room type", y="price", data=AirBnB_cleaned)

In [ ]:
sns.boxplot(x="cancellation policy", y="price", data=AirBnB_cleaned) 

In [ ]:
plt.figure(figsize=(15,10))
sns.boxplot(x="construction year", y="price", data=AirBnB_cleaned)

In [ ]:
sns.boxplot(x="number rooms", y="price", data=AirBnB_cleaned)

_Answer:_ Compared to these five features, increasing the number of rooms would increse the price. Other features have no direct effect to the price.



### Multivariate Analysis (5 points)

As the univariate analysis of price relationships provided only limited insights, you decide to visualize some multivariate investigations of the price. **No matter what you concluded in the last section, you will use the features construction year, number of rooms, cancellation policy, room type, and neighborhood group in the multivariate analysis.**
For each pair of features, create a grouped boxplot (using the hue argument) and investigate whether the two features together allow for an explanation of price differences. In the end, conclude which combination of features should be used to make your pricing decision. 

#### Multivariate Analysis for Neighborhood Group 

In [ ]:
# Your answer goes here
plt.figure(figsize=(20,10))
sns.boxplot(data=AirBnB_cleaned, x="construction year", y="price", hue = "neighborhood group")

In [ ]:
plt.figure(figsize=(20,10))
sns.boxplot(data=AirBnB_cleaned, x="number rooms", y="price", hue = "neighborhood group")

In [ ]:
plt.figure(figsize=(15,5))
sns.boxplot(data=AirBnB_cleaned, x="cancellation policy", y="price", hue = "neighborhood group")

In [ ]:
plt.figure(figsize=(15,5))
sns.boxplot(data=AirBnB_cleaned, x="room type", y="price", hue = "neighborhood group")

_Answer:_ The number of rooms and the neighborhoodgroup would affect the price strongly.



#### Multivariate Analysis for Room Type

In [ ]:
# Your answer goes here
plt.figure(figsize=(20,10))
sns.boxplot(data=AirBnB_cleaned, x="construction year", y="price", hue = "room type")

In [ ]:
plt.figure(figsize=(15,5))
sns.boxplot(data=AirBnB_cleaned, x="cancellation policy", y="price", hue = "room type")

In [ ]:
plt.figure(figsize=(15,5))
sns.boxplot(data=AirBnB_cleaned, x="number rooms", y="price", hue = "room type")

In [ ]:
plt.figure(figsize=(20,10))
sns.boxplot(data=AirBnB_cleaned, x="neighborhood group", y="price", hue = "room type")

_Answer:_ The number of room and the room type would affect the price strongly.


#### Multivariate Analysis for Number of Rooms

In [ ]:
# Your answer goes here
plt.figure(figsize=(20,10))
sns.boxplot(data=AirBnB_cleaned, x="construction year", y="price", hue = "number rooms")


In [ ]:
plt.figure(figsize=(20,10))
sns.boxplot(data=AirBnB_cleaned, x="cancellation policy", y="price", hue = "number rooms")

In [ ]:
plt.figure(figsize=(20,10))
sns.boxplot(data=AirBnB_cleaned, x="room type", y="price", hue = "number rooms")

In [ ]:
plt.figure(figsize=(20,10))
sns.boxplot(data=AirBnB_cleaned, x="neighborhood group", y="price", hue = "number rooms")

_Answer:_ The room type and the number of rooms would affect the price strongly.



#### Multivariate Analysis for Construction Year

In [ ]:
# Your answer goes here
plt.figure(figsize=(20,10))
sns.boxplot(data=AirBnB_cleaned, x="cancellation policy", y="price", hue = "construction year")

In [ ]:
plt.figure(figsize=(20,10))
sns.boxplot(data=AirBnB_cleaned, x="number rooms", y="price", hue = "construction year")

In [ ]:
plt.figure(figsize=(20,10))
sns.boxplot(data=AirBnB_cleaned, x="room type", y="price", hue = "construction year")

In [ ]:
plt.figure(figsize=(20,10))
sns.boxplot(data=AirBnB_cleaned, x="neighborhood group", y="price", hue = "construction year")

_Answer:_ The number of rooms and the construction year would affect the price strongly.



### Selection of Variables (1 point)

Please argue: Which combinations of variables would you consider for pricing your AirBnB?

_Answer:_ The combination of room type and the number of rooms would affect the price directly. However, we need more data about different room type with different number of rooms to confirm my inference.


## Question 2: Setting the Price (45 points)

No matter what you have deducted from your analysis, from now on, you will continue only with three features: **The number of rooms, the neighborhood group, and the room type.**

**Enter Toby**: Toby is your long-term friend back from studying at RWTH. While you studied computer science, Toby studied business administration to become a big shot at Wall Street. He currently works in the back office of some swiss credit institute just across the corner from your office. You decide to drop by and get some of his input for your pricing decision. 

Toby proposes to first use comparables pricing to price your apartment. Comparables pricing is an established concept in economics and means that you price your apartment close to similar apartments. 
You will use different techniques to find similar apartments and set a price.

## Baseline (5 points)

First, you want to set a baseline to compare against. You use the mean absolute error as metric. The baseline should always use the average price of all apartments as a recommended price. Evaluate on a test set of 5%. The same test set should also be used later (you can use the random_state argument in scikit learn's train_test_split, but you need to stay consistent for different questions).

In [3]:
#Take the data we want
data = AirBnB_cleaned.iloc[:,[2,10,12,18]]
data

neighborhood group        room type  price  number rooms
0              Manhattan  Entire home/apt    142             2
1              Manhattan     Private room    620             1
2               Brooklyn  Entire home/apt    368             2
3              Manhattan  Entire home/apt    204             1
4               Brooklyn     Private room     71             1
...                  ...              ...    ...           ...
70837             Queens     Private room    103             1
70838             Queens     Private room    982             1
70839             Queens     Private room    946             1
70840          Manhattan  Entire home/apt   1043             1
70841           Brooklyn  Entire home/apt    809             1

[70842 rows x 4 columns]

In [4]:
#one hot encoder
data_dum = pd.get_dummies(data)
pd.DataFrame(data_dum)
data_dum

price  number rooms  neighborhood group_Bronx  \
0        142             2                         0   
1        620             1                         0   
2        368             2                         0   
3        204             1                         0   
4         71             1                         0   
...      ...           ...                       ...   
70837    103             1                         0   
70838    982             1                         0   
70839    946             1                         0   
70840   1043             1                         0   
70841    809             1                         0   

       neighborhood group_Brooklyn  neighborhood group_Manhattan  \
0                                0                             1   
1                                0                             1   
2                                1                             0   
3                                0                             1   
4                                1                             0   
...                            ...                           ...   
70837                            0                             0   
70838                            0                             0   
70839                            0                             0   
70840                            0                             1   
70841                            1                             0   

       neighborhood group_Queens  neighborhood group_Staten Island  \
0                              0                                 0   
1                              0                                 0   
2                              0                                 0   
3                              0                                 0   
4                              0                                 0   
...                          ...                               ...   
70837                          1                                 0   
70838                          1                                 0   
70839                          1                                 0   
70840                          0                                 0   
70841                          0                                 0   

       room type_Entire home/apt  room type_Hotel room  \
0                              1                     0   
1                              0                     0   
2                              1                     0   
3                              1                     0   
4                              0                     0   
...                          ...                   ...   
70837                          0                     0   
70838                          0                     0   
70839                          0                     0   
70840                          1                     0   
70841                          1                     0   

       room type_Private room  room type_Shared room  
0                           0                      0  
1                           1                      0  
2                           0                      0  
3                           0                      0  
4                           1                      0  
...                       ...                    ...  
70837                       1                      0  
70838                       1                      0  
70839                       1                      0  
70840                       0                      0  
70841                       0                      0  

[70842 rows x 11 columns]

In [5]:
print(data_dum.shape)

(70842, 11)


In [6]:
# Your answer goes here
# data Splitting
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

X = data_dum.iloc[:,1:11] #The number of rooms, the neighborhood group, and the room type
y = data_dum.iloc[:,0] #Price

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.05, random_state = 1, stratify=y)

#print(y_train.value_counts(normalize=True))
#print(y_test.value_counts(normalize=True))


#mean_absolute_error(y_true= , y_pred= )

print(X_train.shape)
print(y_train.shape)
#print(y)


(67299, 10)
(67299,)


In [9]:
# Training
from sklearn import tree
from sklearn.metrics import accuracy_score, f1_score
from sklearn.metrics import confusion_matrix

model = tree.DecisionTreeClassifier(criterion="entropy")  
model.fit(X_train, y_train)

y_pred_decision = model.predict(X_test)

print('Accuracy: %f' % accuracy_score(y_test, y_pred_decision))
print('f1-score: %f' % f1_score(y_test, y_pred_decision, average='weighted'))

print(y_pred_decision)
print(y_test.values)

Accuracy: 0.002822
f1-score: 0.000361
[167 815 815 ... 672 379 379]
[1048  362  685 ...  742  170  160]


## Decision Tree (15 points)

Using a decision tree, you try to price your apartment according to similar apartments. 

In the following, we want to know the price ranges for renting AirBnBs. To use decision trees, you need to discretize prices. We use the following price bins:


- [50, 200]
- (200, 400]
- (400, 600]
- (600, 800]
- (800, 1000]
- (1000, 1200]

We add the attribute "Price_Bins" using the discretization mentioned above for each apartment. For example, if an apartment costs 404, it is put into the bin (400, 600]. **(2 points)**

In [10]:
# Your answer goes here
Price_Bins = pd.cut(AirBnB_cleaned['price'], bins=[50, 200, 400, 600, 800, 1000, 1200], include_lowest=True)
Price_Bins

0         (49.999, 200.0]
1          (600.0, 800.0]
2          (200.0, 400.0]
3          (200.0, 400.0]
4         (49.999, 200.0]
               ...       
70837     (49.999, 200.0]
70838     (800.0, 1000.0]
70839     (800.0, 1000.0]
70840    (1000.0, 1200.0]
70841     (800.0, 1000.0]
Name: price, Length: 70842, dtype: category
Categories (6, interval[float64, right]): [(49.999, 200.0] < (200.0, 400.0] < (400.0, 600.0] < (600.0, 800.0] < (800.0, 1000.0] < (1000.0, 1200.0]]

In [11]:
AirBnB_cleaned.loc[:,'Price_Bins'] = pd.Series(Price_Bins, index=AirBnB_cleaned.index)
AirBnB_cleaned

id      host id neighborhood group        neighborhood       lat  \
0       1002102  52335172823          Manhattan             Midtown  40.75362   
1       1002403  78829239556          Manhattan              Harlem  40.80902   
2       1002755  85098326012           Brooklyn        Clinton Hill  40.68514   
3       1003689  92037596077          Manhattan         East Harlem  40.79851   
4       1004650  61300605564           Brooklyn  Bedford-Stuyvesant  40.68688   
...         ...          ...                ...                 ...       ...   
70837  57353610  69037598918             Queens             Bayside  40.75047   
70838  57358028  56457739998             Queens       East Elmhurst  40.76245   
70839  57358580  60176837202             Queens            Edgemere  40.59380   
70840  57359685  95625271612          Manhattan                SoHo  40.72318   
70841  57360237  83006936257           Brooklyn  Bedford-Stuyvesant  40.69095   

           long        country country code  instant bookable  \
0     -73.98377  United States           US                 0   
1     -73.94190  United States           US                 0   
2     -73.95976  United States           US                 0   
3     -73.94399  United States           US                 0   
4     -73.95596  United States           US                 0   
...         ...            ...          ...               ...   
70837 -73.75349  United States           US                 0   
70838 -73.87938  United States           US                 0   
70839 -73.77373  United States           US                 0   
70840 -74.00223  United States           US                 0   
70841 -73.93444  United States           US                 0   

      cancellation policy        room type  construction year  price  \
0                moderate  Entire home/apt               2007    142   
1                flexible     Private room               2005    620   
2                moderate  Entire home/apt               2005    368   
3                moderate  Entire home/apt               2009    204   
4                moderate     Private room               2015     71   
...                   ...              ...                ...    ...   
70837            moderate     Private room               2007    103   
70838              strict     Private room               2022    982   
70839            moderate     Private room               2020    946   
70840            flexible  Entire home/apt               2020   1043   
70841            flexible  Entire home/apt               2010    809   

       service fee  minimum nights  number of reviews  review rate number  \
0               28               7                 45                   4   
1              124               3                  0                   5   
2               74               7                270                   4   
3               41               7                  9                   3   
4               14               7                 49                   5   
...            ...             ...                ...                 ...   
70837           21               7                 40                   1   
70838          196               1                239                   2   
70839          189               1                 76                   1   
70840          209               2                 21                   4   
70841          162               7                  4                   1   

       calculated host listings count  number rooms        Price_Bins  
0                                   2             2   (49.999, 200.0]  
1                                   1             1    (600.0, 800.0]  
2                                   1             2    (200.0, 400.0]  
3                                   1             1    (200.0, 400.0]  
4                                   1             1   (49.999, 200.0]  
...                               ...

Consider the extended dataset from the previous task. Use 'number rooms,' 'room type,' and 'neighborhood group' as descriptive features and "Price_Bins" as the target feature. Create a test and training set like before. **(0.5 point)**

In [12]:
data = AirBnB_cleaned.iloc[:,[2,10,18,19]]
data

neighborhood group        room type  number rooms        Price_Bins
0              Manhattan  Entire home/apt             2   (49.999, 200.0]
1              Manhattan     Private room             1    (600.0, 800.0]
2               Brooklyn  Entire home/apt             2    (200.0, 400.0]
3              Manhattan  Entire home/apt             1    (200.0, 400.0]
4               Brooklyn     Private room             1   (49.999, 200.0]
...                  ...              ...           ...               ...
70837             Queens     Private room             1   (49.999, 200.0]
70838             Queens     Private room             1   (800.0, 1000.0]
70839             Queens     Private room             1   (800.0, 1000.0]
70840          Manhattan  Entire home/apt             1  (1000.0, 1200.0]
70841           Brooklyn  Entire home/apt             1   (800.0, 1000.0]

[70842 rows x 4 columns]

In [13]:
#one hot encoder
data_dum = pd.get_dummies(data)
#pd.DataFrame(data_dum)
data_dum

number rooms  neighborhood group_Bronx  neighborhood group_Brooklyn  \
0                 2                         0                            0   
1                 1                         0                            0   
2                 2                         0                            1   
3                 1                         0                            0   
4                 1                         0                            1   
...             ...                       ...                          ...   
70837             1                         0                            0   
70838             1                         0                            0   
70839             1                         0                            0   
70840             1                         0                            0   
70841             1                         0                            1   

       neighborhood group_Manhattan  neighborhood group_Queens  \
0                                 1                          0   
1                                 1                          0   
2                                 0                          0   
3                                 1                          0   
4                                 0                          0   
...                             ...                        ...   
70837                             0                          1   
70838                             0                          1   
70839                             0                          1   
70840                             1                          0   
70841                             0                          0   

       neighborhood group_Staten Island  room type_Entire home/apt  \
0                                     0                          1   
1                                     0                          0   
2                                     0                          1   
3                                     0                          1   
4                                     0                          0   
...                                 ...                        ...   
70837                                 0                          0   
70838                                 0                          0   
70839                                 0                          0   
70840                                 0                          1   
70841                                 0                          1   

       room type_Hotel room  room type_Private room  room type_Shared room  \
0                         0                       0                      0   
1                         0                       1                      0   
2                         0                       0                      0   
3                         0                       0                      0   
4                         0                       1                      0   
...                     ...                     ...                    ...   
70837                     0                       1                      0   
70838                     0                       1                      0   
70839                     0                       1                      0   
70840                     0                       0                      0   
70841                     0                       0                      0   

       Price_Bins_(49.999, 200.0]  Price_Bins_(200.0, 400.0]  \
0                               1                          0   
1                               0                          0   
2                               0                          1   
3                               0                          1   
4                               1                          0   
...                           ...                        ...   
70837                           1                  

In [14]:
print(data_dum.shape)

(70842, 16)


In [15]:
# data Splitting
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

X = data_dum.iloc[:,0:10] #The number of rooms, the neighborhood group, and the room type
y = data_dum.iloc[:,10:17] #Price

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.05, random_state = 1)

#print(y_train.value_counts(normalize=True))
#print(y_test.value_counts(normalize=True))


#mean_absolute_error(y_true= , y_pred= )

print(X_train.shape)
print(y_train.shape)
#print(y_train)

(67299, 10)
(67299, 6)


In [16]:
# Training
from sklearn import tree
from sklearn.metrics import accuracy_score, f1_score
from sklearn.metrics import confusion_matrix

model = tree.DecisionTreeClassifier(criterion="entropy")  
clf = model.fit(X_train, y_train)
#tree.plot_tree(clf)

y_pred_decision = model.predict(X_test)

print('Accuracy: %f' % accuracy_score(y_test, y_pred_decision))
print('f1-score: %f' % f1_score(y_test, y_pred_decision, average='weighted'))

print(y_pred_decision)
print(y_test.values)


Accuracy: 0.022580
f1-score: 0.037023
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 ...
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 1]
 ...
 [0 0 0 0 0 1]
 [0 0 0 1 0 0]
 [0 0 0 0 0 1]]


Generate a decision tree in which the minimum number of samples for splitting is ten and use entropy. What is the system's entropy? **(5 points)**

Note: For this task, you must use the p_decision_tree library.

In [18]:
# Your answer goes here
model = tree.DecisionTreeClassifier(min_samples_split=10, criterion="entropy")  
model.fit(X_train, y_train)

y_pred_decision = model.predict(X_test)

print('Accuracy: %f' % accuracy_score(y_test, y_pred_decision))
print('f1-score: %f' % f1_score(y_test, y_pred_decision, average='weighted'))

print(y_pred_decision)
print(y_test.values)


Accuracy: 0.022580
f1-score: 0.037023
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 ...
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 1]
 ...
 [0 0 0 0 0 1]
 [0 0 0 1 0 0]
 [0 0 0 0 0 1]]


In [19]:
import graphviz
from subprocess import check_output

column_names = list(X_train.columns.values)
#del column_names[-1]
dot_file = "Classification.dot"
pdf_file = "Classification.pdf"
with open(dot_file, "w") as f:
    f = tree.export_graphviz(model, out_file=f, 
                                 feature_names= column_names, 
                                 class_names=["(49.999, 200.0]", "(200.0, 400.0]", "(400.0, 600.0]", "(600.0, 800.0]", "(800.0, 1000.0]", "(1000.0, 1200.0]"], 
                                 filled=True, rounded=True)
try:
    check_output("dot -Tpdf "+ dot_file + " -o " + pdf_file , shell=True)
    print("Find Classification.dot (description) and Classification.pdf (visual tree) in the home page of your Jupyter.")
except:
    print("Make sure that you have installed Graphviz, otherwise you can not see the visual tree. But you can find descriptions in a dot file")


Find Classification.dot (description) and Classification.pdf (visual tree) in the home page of your Jupyter.


In [21]:
columns = data.columns

#All columns except the last one are descriptive by default
descriptive_features = columns[:-1]
#print(descriptive_features)
#The last column is considered as label
label = columns[-1]

#Converting all the columns to string
for column in columns:
    data[column]= data[column].astype(str)
    #print(data[column])

data_descriptive = data[descriptive_features].values
#print(descriptive_features)
data_label = data[label].values
#print(data_label)

print("descriptive features:")
print(descriptive_features)
print("\ntarget feature:\n" + label)

descriptive features:
Index(['neighborhood group', 'room type', 'number rooms'], dtype='object')

target feature:
Price_Bins


/var/folders/j8/8ppl6wh96296jgnc1sqt5lnm0000gn/T/ipykernel_74032/880549322.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[column]= data[column].astype(str)


In [22]:
from p_decision_tree.DecisionTree import DecisionTree

decisionTree = DecisionTree(data_descriptive.tolist(), descriptive_features.tolist(), data_label.tolist(), "entropy")

#Calling DecisionTree constructor (the last parameter is criterion which can also be "gini")
decisionTree = DecisionTree(data_descriptive.tolist(), descriptive_features.tolist(), data_label.tolist(), "entropy")

#Here you can pass pruning features (gain_threshold and minimum_samples)
decisionTree.id3(0,0)

#Visualizing decision tree by Graphviz
dot = decisionTree.print_visualTree( render=True )

print(dot)

print("System entropy: ", format(decisionTree.entropy))
print("System gini: ", format(decisionTree.gini))


// Decision Tree
digraph {
	root [label="number rooms"]
	0.5740034454874701 [label=2]
	root -> 0.5740034454874701
	0.6343578183348615 [label="neighborhood group"]
	0.5740034454874701 -> 0.6343578183348615
	0.9358510558600377 [label=1]
	root -> 0.9358510558600377
	0.9946652109655765 [label="room type"]
	0.9358510558600377 -> 0.9946652109655765
	0.8478483281896888 [label=3]
	root -> 0.8478483281896888
	0.2661246097943831 [label="neighborhood group"]
	0.8478483281896888 -> 0.2661246097943831
	0.4361945605324271 [label=4]
	root -> 0.4361945605324271
	0.19541866477279546 [label="neighborhood group"]
	0.4361945605324271 -> 0.19541866477279546
	0.6343578183348615 [label="neighborhood group"]
	0.7725724973698416 [label=Manhattan]
	0.6343578183348615 -> 0.7725724973698416
	0.9318878027706581 [label="room type"]
	0.7725724973698416 -> 0.9318878027706581
	0.9863633099104002 [label=Brooklyn]
	0.6343578183348615 -> 0.9863633099104002
	0.11434507929585214 [label="room type"]
	0.9863633099104002 -> 0

What is the first feature the decision tree splits on? **(0.5 point)**

_Answer:_ Room type



Since it doesn't make sense to set a price range for renting a room, we need to fix a price. For simplicity, we use the means of the bins, i.e., 125, 300, 500, 700, 900, and 1100. For example, if a room were categorized in the bin (200, 400], it would have the price of 300.

What prices are possible given your decision tree for:

- Manhattan, 1-room, Private room: 500
- Staten Island, 1-room, Shared room: 700 

**(1 point)**

In [ ]:
print(X_test.shape)

_Answer:_



What is the proposed price of the decision tree for our apartment? Store it in a variable for later usage. **(1 point)**

In [ ]:
# Your answer goes here


To evaluate how good our decision tree is for determining price categories, we want to measure the error of the predictions on the test set. To do so, the IDS team provided you helper functions below.

In [24]:
import pydotplus
import networkx

In [25]:
def get_name_value_dict(graph):
    id_label_dict = {}
    root = decisionTree.root
    visited = set() # Set to keep track of visited nodes of graph.

    def dfs(visited, graph, node):#function for dfs 
        id_label_dict[node.name] = node.value
        if node not in visited:
            if node.next:
                id_label_dict[node.next.name] = node.next.value
            visited.add(node)
            if node.childs:
                for child in node.childs:
                    if child is not None:
                        dfs(visited, graph, child)
            elif node.next:
                if node.next.childs:
                    for child in node.next.childs:
                        if child is not None:
                            dfs(visited, graph, child)
    dfs(visited, graph, root)
    return id_label_dict

def get_predictor(tree):
  id_label_dict = get_name_value_dict(tree)
  dotplus = pydotplus.graph_from_dot_data(tree.source)
  G = networkx.nx_pydot.from_pydot(dotplus)
  root = [n for n,d in G.in_degree() if d==0][0]
  paths = []
  for node in G:
      if G.out_degree(node)==0: #it's a leaf
          paths.append(networkx.shortest_path(G, root, node))
  new_paths = []
  for path in paths:
      for name, value in id_label_dict.items():
          path = ([p.replace(name, value) for p in path])
      new_paths.append(path)
  predictor = {}
  for path in new_paths.copy():
    target = path[-1]
    classification = tuple(path[:-1])
    predictor[classification] = target
  return predictor

def get_prediction_features(predictor):
    features = set()
    for key in predictor:
        i = 0
        while i <= len(key)-2:
            features.add(key[i])
            i +=2
    return features
            
def get_predicted_bin(instance, features, predictor):
  feature_values = {}
  for feature in features:
      feature_values[feature] = instance[feature]
  possible_paths = predictor.keys()
  i=0
  while i<2*len(feature_values):
    attribute = [path[i] for path in possible_paths][0]
    if attribute in predictor.values():
      break
    feature_value = feature_values[attribute]
    candidates = []
    for el in possible_paths:
      if str(el[i+1]) == str(feature_value):
        candidates.append(el)
    possible_paths = candidates.copy()
    i+=2
  return predictor[possible_paths[0]]



### Dot is your visual decision tree. Adjust the naming if needed
predictor = get_predictor(dot)
features = get_prediction_features(predictor)

#dot_file = "Classification.dot"
#pdf_file = "Classification.pdf"

To predict the price bin for each instance of your test set, apply the function get_predicted_bin using the variables *predictor* and *features* provided above. **(2 points)**

In [ ]:
# Your answer goes here


You predicted a price range for AirBnBs in your test set. However, since you cannot enter a price range for renting an apartment, we have to map the range of bins to one value. To do so, we use the mean of bins, as explained before, to predict the price. Given that, compute the mean absolute error between the prediction from the decision tree and the real price provided in the dataset. What is the mean absolute error? **(3 points)**

In [ ]:
# Your answer goes here


## Clustering (23 points)

Another way to do comparables pricing is to find similar apartments using clustering. Each calculated cluster represents one or more similar apartments in the dataset. For each cluster, you calculate the mean price as a representative price. To predict the price for new apartments, you assign them to an existing cluster and give the mean price as prediction.

Use the same features you used in the decision tree for the clustering as well (**number rooms, neighborhood group, room type**), and remember that your dataset is still split into a training and test set.

In this task, you will use the k-means algorithm.
*Note: To keep results comparable, please use 100 for random state and n_init when initializing the clustering algorithm. Also, remember to use the same test and training set as in the previous tasks to compare performances.*

### Encoding (2 points)

K-means tries to calculate the distance between different data points. Since some of the features you want to use are not numeric, apply one-hot encoding to be able to use distance measures. Use the preprocessing module of sklearn to prepare your dataset for clustering.

In [ ]:
# Your answer goes here


### Choosing number of clusters (8 points)

In k-means, the number of wanted clusters is a parameter one can decide on. Since this is information you do not have at this time, you choose to use the data to decide.

You cluster on the training dataset by using `k` number of clusters where `k` is between 4 and 15. Since you are interested in the price, for each clustering, you calculate the **standard deviation of the mean prices for the clusters**. Therefore, for each clustering:
1. Calculate the mean price for each of the resulting clusters.
2. Calculate the standard deviation of the mean prices calculated in 1.

Plot a diagram where on the `x-axis` you will have the *number of clusters used* and on the `y-axis` the *standard deviation of the means*.

In your opinion, which amount of clusters makes more sense? Explain your answer.

In [ ]:
# Your answer goes here


_Answer:_



**Note:** No matter the conclusion made in the previous task, from now on, you use the clustering model with **9 clusters** for predicting the price for your apartment and evaluating the clustering technique.

### Pricing your apartment (3 points)

To predict the price for your apartment, calculate in which cluster your apartment would be and use the mean value of the cluster as a possible price.

In [ ]:
# Your answer goes here
# cluster for 9 clusters


### Evaluating clustering (10 points)

You want to evaluate how well your clustering worked. In your case, two things can be evaluated:

1.   Whether the clustering technique can group similar apartments together
2.   Whether other people determine the price of their apartment as you did, meaning whether similar apartments get a similar price

You are going to evaluate the clustering technique visually. The IDS team provides you with the following fancy code that reduces your input to two dimensions.

In [ ]:
import umap.umap_ as umap

#Preprocessing numerical
full_data = x_train # use the train dataset here
numerical = full_data.select_dtypes(exclude='object')

for c in numerical.columns:
    pt = sklearn.preprocessing.PowerTransformer()
    numerical.loc[:, c] = pt.fit_transform(np.array(numerical[c]).reshape(-1, 1))
    
##preprocessing categorical
categorical = full_data.select_dtypes(include='object')
categorical = pd.get_dummies(categorical)

#Percentage of columns which are categorical is used as weight parameter in embeddings later
categorical_weight = len(full_data.select_dtypes(include='object').columns) / full_data.shape[1]

#Embedding numerical & categorical
fit1 = umap.UMAP(metric='l2').fit(numerical)
fit2 = umap.UMAP(metric='dice').fit(categorical)

#Augmenting the numerical embedding with categorical
intersection = umap.general_simplicial_set_intersection(fit1.graph_, fit2.graph_, weight=categorical_weight)
intersection = umap.reset_local_connectivity(intersection)
embedding = umap.simplicial_set_embedding(fit1._raw_data, intersection, fit1.n_components,
                                                fit1._initial_alpha, fit1._a, fit1._b,
                                                fit1.repulsion_strength, fit1.negative_sample_rate,
                                                200, 'random', np.random, fit1.metric,
                                                fit1._metric_kwds, False, {}, False)

# Extracting the resulting dimensions
dimension1 = embedding[0].T[0]
dimension2 = embedding[0].T[1]

Create a scatter plot from the two dimensions and use the cluster labels for coloring the data points. Use the train set for the visualization. Discuss the result. **(5 points)**

In [ ]:
# Your answer goes here


_Answer:_



We next evaluate whether similar apartments (considering the attributes we chose) get similar prices. To do this, we use our test set. Assign each apartment of the test set to the nearest centroid. Predict the price of the apartments in the test set by taking the mean price of the cluster they was assigned to. Calculate the mean absolute error between the predicted and real prices. **(5 points)**

In [ ]:
# Your answer goes here


## Final comments on the price prediction (2 points)

Please compare the three approaches used for determining the price. Do they provide a good way of determining the price?

_Answer:_



## Question 3: Investigating Price Elasticity (32 Points)

You show your results to Toby, excited about the price suggestions you got from the decision tree and clustering. You decide to take the higher price, which naturally means more income.

However, he points you to one central flaw in your thinking: The number of bookings is not independent of the price. Therefore, you can not just take any price and assume that this will lead to more income than a lower price, as the demand (utilization) for your apartment might decrease. This is called **price elasticity**.

You want to verify what Toby has been telling you. You extracted the utilization column of your dataset by grabbing the available data from AirBnB's calendar (smart!). The utilization values are contained in dataset **AirBnB_utilization.csv**. **Show several graphs investigating price elasticity.** For example, you might plot the utilization in relation to the price and color according to different variable values. 
After you have verified Toby's statements, you want to learn price elasticity from the dataset (the utilization of an apartment given the price, the number of rooms, the room type, and the neighborhood group, i.e., the same features as before). With the learned price elasticity, you want to evaluate which of the proposed prices (decision tree or clustering) is the better choice. **(2 points)**

In [ ]:
# Your answer goes here


You will investigate the relationship between price and utilization in this subtask. First, you will train different models and choose the one that best predicts utilization for an apartment. Second, you will evaluate which of the proposed prices of decision tree and clustering prices were better, assuming that your model provides the correct utilization. Third, you will conclude your investigation and provide a pricing decision.

### Learning price elasticity (25 points)
You want to use different supervised learning techniques to learn price elasticity. You decide on linear regression, SVM, and multilayer perceptrons. However, you have to preprocess the data. Use the features of the neighborhood group, the room type, the number of rooms, and the price to predict the utilization. Split into training and testing data (test size 5%).

#### Prepare the data set by splitting, one-hot encoding, and normalizing. (5 points)

In [ ]:
# Your answer goes here


For each technique, use 5-cross-fold validation for hyperparameter optimization and assess the performance on the test set. 

#### Regression (5 points)

Learn a linear regression to predict the utilization of an AirBnB.

In [ ]:
# Your answer goes here


What is the mean absolute error achieved on the test data?

In [ ]:
# Your answer goes here


Show (draw!) the price elasticity for your apartment. 

In [ ]:
# Your answer goes here


#### Linear SVR (5 points)

Train and evaluate a Linear SVR (Support Vector Regression) model.

In [ ]:
# Your answer goes here


What is the mean absolute error achieved on the test data?

In [ ]:
# Your answer goes here


Show (draw!) the price elasticity for your apartment. 

In [ ]:
# Your answer goes here


#### Learning Non-Linear Relationships

You realize that learning linear relationships only provides limited performance. You want to learn non-linear relationships. First, you will learn non-linear relationships using linear regression and kernels. Second, you will use non-linear kernels in the Support Vector Regression. Third, you will use neural networks.

#### Kernels in Regression (2.5 points)

Use a transformation of the price and a regression to incorporate non-linear relationships, as learned in the lecture. You can try different kernel functions, but at least you should use one quadratic kernel.

In [ ]:
# Your answer goes here


What is the mean absolute error achieved on the test data?

In [ ]:
# Your answer goes here


Show (draw!) the price elasticity for your apartment. 

In [ ]:
# Your answer goes here


#### Kernels in SVR (2.5 points)

Train and evaluate an SVR (Support Vector Regression) model with different, non-linear kernels. You can limit the size of your training set to 25000 samples to make the problem feasible in computation time.

In [ ]:
# Your answer goes here


What is the mean absolute error achieved on the test data?

In [ ]:
# Your answer goes here


Show (draw!) the price elasticity for your apartment. 

In [ ]:
# Your answer goes here


What is your conclusion on using kernels?

_Answer:_



#### Neural Network (5 points)

Learn a neural network (multilayer perceptron) to predict the utilization of an AirBnB.

In [ ]:
# Your answer goes here


What is the mean absolute error achieved on the test data?

In [ ]:
# Your answer goes here


Show (draw!) the price elasticity for your apartment. 

In [ ]:
# Your answer goes here


### Profit discrepencies when incorporating price elasticity (5 points)

Use the model that best captures price elasticity on the testing set. You can assume that this model accurately captures price elasticity, i.e., is the ground truth. What is the better of the two proposed prices? Is the better price the optimal price?

In [ ]:
# Your answer goes here


_Answer:_



# Question 4: Conclusion (5 points)

Summarize your findings and discuss limitations.

_Answer:_ 

